### ISSUE TITLE
Example of using requestAnimationFrame

### ISSUE THREAD

**Issue by benjaminreid** [kapv89/react-native-timer#2]
Hello 👋,

I’m having a little trouble using the `requestAnimationFrame` (RAF) portion of your library, the rest works really well so thank you for that 🙌 

I’d typically write a RAF loop like so...

```js
(function run() {
  requestAnimationFrame(run);
  console.log("Running...");
})();
```

So, I thought with your library it’d work _almost_ like a drop in replacement. But I’m having no luck. Using this as an example, the `console.log` gets run once or twice and that’s it, no looping happens as expected.

```js
(function run() {
  timer.requestAnimationFrame("run", run);
  console.log("Running...");
})();
```

Any help would be greatly appreciated! I’ve seen the example in the README which does have `requestAnimationFrame` but funnily not your implementation? 🙃

**Comment by kapv89** [comment]
Let me look into it.

**Comment by kapv89** [comment]
Just pushed version `1.3.3`, which fixes this(tested in a UI env). Would be great if you can confirm that the fix works for you. There was some issue with how memory was being freed up after the execution of `timer.setTimeout`, `timer.setImmediate`, and `timer.requestAnimationFrame`, which prevented looping behavior. Pushed some changes to free up memory before the execution of the callback, which in turn allows looping. Had to keep track of which callbacks are being executed in order to ensure proper behavior of `*Exists` methods.

**Comment by benjaminreid** [comment]
@kapv89 This is now working as expected, thank you for fixing it so fast!
